[pytest]
testpaths =
    tests/unit

# Avoid "PytestUnknownMarkWarning: Unknown pytest.mark.asyncio"
markers =
    asyncio: mark test as requiring an asyncio event loop

# Let pytest-asyncio decide the best loop handling automatically.
asyncio_mode = auto

