from abc import ABC, abstractmethod


class VectorDBBase(ABC):
    @abstractmethod
    async def create_collection(self, name: str, dimension: int, **kwargs) -> dict: ...
    @abstractmethod
    async def drop_collection(self, name: str) -> dict: ...
    @abstractmethod
    async def insert(self, collection: str, data: list[dict], **kwargs) -> dict: ...
    @abstractmethod
    async def search(self, collection: str, vector: list[float], top_k: int = 10, **kwargs) -> dict: ...
    @abstractmethod
    async def query(self, collection: str, filter_expr: str, **kwargs) -> dict: ...
    @abstractmethod
    async def delete(self, collection: str, ids: list[str], **kwargs) -> dict: ...
    @abstractmethod
    async def upsert(self, collection: str, data: list[dict], **kwargs) -> dict: ...
    @abstractmethod
    async def flush(self, collection: str) -> dict: ...
    @abstractmethod
    async def load_collection(self, name: str) -> dict: ...
    @abstractmethod
    async def release_collection(self, name: str) -> dict: ...
    @abstractmethod
    async def get_collection_info(self, name: str) -> dict: ...
    @abstractmethod
    async def list_collections(self) -> list[str]: ...
    @abstractmethod
    async def health_check(self) -> dict: ...
    @abstractmethod
    async def close(self) -> None: ...
