import numpy as np
from typing import List
from src.state import WorkflowState

class SemanticCoverageMonitor:
    """
    Evaluates the trajectory of test cases generated by Agent 2.
    If generated vectors collapse into a local mode (high similarity),
    injects a forced mutation prompt to encourage exploration.
    """
    
    def __init__(self, similarity_threshold: float = 0.9, history_limit: int = 100):
        self.similarity_threshold = similarity_threshold
        self.history_limit = history_limit
        
    def _cosine_similarity(self, v1: List[float], v2: List[float]) -> float:
        """Compute cosine similarity between two vectors."""
        if not v1 or not v2:
            return 0.0
        # Ensure they are same length
        min_len = min(len(v1), len(v2))
        a = np.array(v1[:min_len])
        b = np.array(v2[:min_len])
        norm_a = np.linalg.norm(a)
        norm_b = np.linalg.norm(b)
        if norm_a == 0 or norm_b == 0:
            return 0.0
        return float(np.dot(a, b) / (norm_a * norm_b))

    def evaluate_and_mutate(self, state: WorkflowState) -> WorkflowState:
        """
        Evaluate current test cases against history.
        If mode collapse is detected, mutate the state's fuzzing_feedback.
        """
        if not state.current_test_cases:
            return state
            
        # Extract new vectors from current test cases
        new_vectors = []
        for tc in state.current_test_cases:
            is_dict = isinstance(tc, dict)
            vec = tc.get('query_vector') if is_dict else tc.query_vector
            if vec:
                new_vectors.append(vec)
                
        if not new_vectors:
            return state
            
        # Check similarity against history
        mode_collapse_detected = False
        if state.history_vectors:
            for new_vec in new_vectors:
                # Compare against the most recent history vectors
                recent_history = state.history_vectors[-20:] 
                similarities = [self._cosine_similarity(new_vec, h_vec) for h_vec in recent_history]
                avg_sim = sum(similarities) / len(similarities) if similarities else 0.0
                
                if avg_sim > self.similarity_threshold:
                    mode_collapse_detected = True
                    print(f"[Coverage Monitor] Mode collapse detected! Average similarity: {avg_sim:.2f}")
                    break
                    
        # Update history
        state.history_vectors.extend(new_vectors)
        # Prune history to limit memory usage
        if len(state.history_vectors) > self.history_limit:
            state.history_vectors = state.history_vectors[-self.history_limit:]
            
        # Inject Mutation Prompt if needed
        if mode_collapse_detected:
            mutation_prompt = (
                "\n\n[SYSTEM OVERRIDE: FORCED MUTATION]\n"
                "Your recent test case generations are too similar to previous ones (Mode Collapse). "
                "You MUST drastically change your test generation strategy for this round. "
                "Explore completely different dimensions, use entirely different semantic intents, "
                "or generate extreme adversarial inputs (e.g., highly sparse vectors, negative values, "
                "or edge-case parameter combinations). Break out of your current pattern!"
            )
            
            # Append to existing feedback or overwrite
            if state.fuzzing_feedback:
                state.fuzzing_feedback += mutation_prompt
            else:
                state.fuzzing_feedback = mutation_prompt
                
        return state

def run_coverage_monitor(state: WorkflowState) -> WorkflowState:
    monitor = SemanticCoverageMonitor()
    return monitor.evaluate_and_mutate(state)